/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import MODELO.Cliente;
/**
 *
 * @author robin
 */
public class frm_persona extends javax.swing.JFrame {

    /**
     * Creates new form frm_persona
     */
    Cliente obj_Cliente;
    public frm_persona() {
        initComponents();
        obj_Cliente = new Cliente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EMPLEADOS = new javax.swing.JTabbedPane();
        LBLDIRECCION = new javax.swing.JPanel();
        LBLTITULO = new javax.swing.JLabel();
        LBL_NIT = new javax.swing.JLabel();
        LBL_NOMBRE = new javax.swing.JLabel();
        LBL_APELLIDO = new javax.swing.JLabel();
        LBL_DIRECCION = new javax.swing.JLabel();
        LBL_TELEFONO = new javax.swing.JLabel();
        LBL_NACIMIENTO = new javax.swing.JLabel();
        BTT_GUARDAR = new javax.swing.JButton();
        TXT_NIT = new javax.swing.JTextField();
        TXT_NOMBRE = new javax.swing.JTextField();
        TXT_APELLIDOS = new javax.swing.JTextField();
        TXT_DIRECCION = new javax.swing.JTextField();
        TXT_TELEFONO = new javax.swing.JTextField();
        TXT_NACIMIENTO = new javax.swing.JTextField();
        BTT_MODIFICAR = new javax.swing.JButton();
        PANEL_EMPLEADOS = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LBLTITULO.setText("FORMULARIO CLIENTE");

        LBL_NIT.setText("NIT");

        LBL_NOMBRE.setText("NOMBRE");

        LBL_APELLIDO.setText("APELLIDOS");

        LBL_DIRECCION.setText("DIRECCION");

        LBL_TELEFONO.setText("TELEFONO");

        LBL_NACIMIENTO.setText("NACIMIENTO");

        BTT_GUARDAR.setForeground(new java.awt.Color(0, 0, 204));
        BTT_GUARDAR.setText("GUARDAR");
        BTT_GUARDAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTT_GUARDARActionPerformed(evt);
            }
        });

        TXT_NIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_NITActionPerformed(evt);
            }
        });

        BTT_MODIFICAR.setForeground(new java.awt.Color(0, 0, 255));
        BTT_MODIFICAR.setText("MODIFICAR");
        BTT_MODIFICAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTT_MODIFICARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LBLDIRECCIONLayout = new javax.swing.GroupLayout(LBLDIRECCION);
        LBLDIRECCION.setLayout(LBLDIRECCIONLayout);
        LBLDIRECCIONLayout.setHorizontalGroup(
            LBLDIRECCIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LBLDIRECCIONLayout.createSequentialGroup()
                .addGroup(LBLDIRECCIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LBLDIRECCIONLayout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(LBLTITULO))
                    .addGroup(LBLDIRECCIONLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(LBLDIRECCIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBL_DIRECCION)
                            .addComponent(LBL_TELEFONO)
                            .addComponent(LBL_NACIMIENTO)
                            .addGroup(LBLDIRECCIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(LBL_NIT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LBL_NOMBRE)
                                .addComponent(LBL_APELLIDO, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)))
                        .addGap(117, 117, 117)
                        .addGroup(LBLDIRECCIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BTT_GUARDAR)
                            .addGroup(LBLDIRECCIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(LBLDIRECCIONLayout.createSequentialGroup()
                                    .addComponent(TXT_NIT, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                                    .addComponent(BTT_MODIFICAR))
                                .addComponent(TXT_NOMBRE)
                                .addComponent(TXT_APELLIDOS)
                                .addComponent(TXT_DIRECCION)
                                .addComponent(TXT_TELEFONO)
                                .addComponent(TXT_NACIMIENTO)))))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        LBLDIRECCIONLayout.setVerticalGroup(
            LBLDIRECCIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LBLDIRECCIONLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(LBLTITULO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(LBLDIRECCIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBL_NIT)
                    .addGroup(LBLDIRECCIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TXT_NIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BTT_MODIFICAR)))
                .addGap(17, 17, 17)
                .addGroup(LBLDIRECCIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBL_NOMBRE)
                    .addComponent(TXT_NOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(LBLDIRECCIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBL_APELLIDO)
                    .addComponent(TXT_APELLIDOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(LBLDIRECCIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBL_DIRECCION)
                    .addComponent(TXT_DIRECCION, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(LBLDIRECCIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBL_TELEFONO)
                    .addComponent(TXT_TELEFONO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(LBLDIRECCIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBL_NACIMIENTO)
                    .addComponent(TXT_NACIMIENTO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BTT_GUARDAR)
                .addContainerGap(248, Short.MAX_VALUE))
        );

        EMPLEADOS.addTab("CLIENTES", LBLDIRECCION);

        javax.swing.GroupLayout PANEL_EMPLEADOSLayout = new javax.swing.GroupLayout(PANEL_EMPLEADOS);
        PANEL_EMPLEADOS.setLayout(PANEL_EMPLEADOSLayout);
        PANEL_EMPLEADOSLayout.setHorizontalGroup(
            PANEL_EMPLEADOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        PANEL_EMPLEADOSLayout.setVerticalGroup(
            PANEL_EMPLEADOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 567, Short.MAX_VALUE)
        );

        EMPLEADOS.addTab("EMPLEADOS", PANEL_EMPLEADOS);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EMPLEADOS)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EMPLEADOS)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXT_NITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_NITActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_NITActionPerformed

    private void BTT_GUARDARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTT_GUARDARActionPerformed
        obj_Cliente =  new Cliente(TXT_NIT.getText(), TXT_NOMBRE.getText(), TXT_APELLIDOS.getText(), TXT_DIRECCION.getText(), TXT_TELEFONO.getText(), TXT_NACIMIENTO.getText());
        obj_Cliente.agregar();
    }//GEN-LAST:event_BTT_GUARDARActionPerformed

    private void BTT_MODIFICARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTT_MODIFICARActionPerformed
        // TODO add your handling code here:
        obj_Cliente.setNit(TXT_NIT.getText());
        obj_Cliente.agregar();
    }//GEN-LAST:event_BTT_MODIFICARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_persona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTT_GUARDAR;
    private javax.swing.JButton BTT_MODIFICAR;
    private javax.swing.JTabbedPane EMPLEADOS;
    private javax.swing.JPanel LBLDIRECCION;
    private javax.swing.JLabel LBLTITULO;
    private javax.swing.JLabel LBL_APELLIDO;
    private javax.swing.JLabel LBL_DIRECCION;
    private javax.swing.JLabel LBL_NACIMIENTO;
    private javax.swing.JLabel LBL_NIT;
    private javax.swing.JLabel LBL_NOMBRE;
    private javax.swing.JLabel LBL_TELEFONO;
    private javax.swing.JPanel PANEL_EMPLEADOS;
    private javax.swing.JTextField TXT_APELLIDOS;
    private javax.swing.JTextField TXT_DIRECCION;
    private javax.swing.JTextField TXT_NACIMIENTO;
    private javax.swing.JTextField TXT_NIT;
    private javax.swing.JTextField TXT_NOMBRE;
    private javax.swing.JTextField TXT_TELEFONO;
    // End of variables declaration//GEN-END:variables
}
